---
- name: Add HashiCorp APT key
  ansible.builtin.apt_key:
    id: 798AEC654E5C15428C8E42EEAA16FCBCA621E701
    url: https://apt.releases.hashicorp.com/gpg

- name: Add HashiCorp APT repo
  ansible.builtin.apt_repository:
    repo: >
      deb https://apt.releases.hashicorp.com
      {{ ansible_distribution_release }} main
    update_cache: true

- name: Install Vagrant from APT package
  ansible.builtin.package:
    name: vagrant
